image_width: 320
image_height: 240
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [275.30961,   0.     , 161.69245,
           0.     , 275.51367, 104.97604,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.032681, -0.035129, -0.002072, -0.007272, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [276.97601,   0.     , 158.946  ,   0.     ,
           0.     , 278.4985 , 104.02284,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
